runtime: python310

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  entrypoint: gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 8080 main:application
